# https://gohugo.io/getting-started/configuration/#baseurl
baseURL: "https://rolandsdev.blog/"

# https://gohugo.io/getting-started/configuration/#defaultcontentlanguage
defaultContentLanguage: "en"
# https://gohugo.io/getting-started/configuration/#languagecode
languageCode: "en"

# https://gohugo.io/getting-started/configuration/#title
title: "Roland's Dev Blog"

# https://gohugo.io/getting-started/configuration/#theme
theme: "DoIt"

# https://gohugo.io/getting-started/configuration/#enablegitinfo
enableGitInfo: yes
# https://gohugo.io/getting-started/configuration/#enablerobotstxt
enableRobotsTXT: yes

# https://gohugo.io/getting-started/configuration/#enableemoji
enableEmoji: yes

# https://gohugo.io/content-management/menus/
menu:
  main:
    - identifier: "posts"
      pre: ""
      post: ""
      name: "Posts"
      url: "/posts/"
      title: ""
      weight: 1
    - identifier: "tags"
      pre: ""
      post: ""
      name: "Tags"
      url: "/tags/"
      title: ""
      weight: 2
    - identifier: "categories"
      pre: ""
      post: ""
      name: "Categories"
      url: "/categories/"
      title: ""
      weight: 3
    - identifier: "series"
      pre: ""
      post: ""
      name: "Series"
      url: "/series/"
      title: ""
      weight: 4
    - identifier: "github"
      pre: "<i class='fab fa-github fa-fw'></i>"
      post: ""
      name: ""
      url: "https://github.com/rolandjitsu"
      title: "GitHub"
      weight: 5

# https://gohugo.io/getting-started/configuration/#markup
# https://gohugo.io/getting-started/configuration-markup
markup:
  highlight:
    codeFences: yes
    lineNoStart: 1
    lineNos: yes
    noClasses: no
    style: vs
    tabWidth: 2

# https://hugodoit.pages.dev/theme-documentation-basics/#site-configuration
params:
  version: "0.2.X"

  title: ""
  description: "A collection of dev guides, tutorials and thoughts on various tech stacks, tools and programming languages."

  # "light"/"dark"/"black"/"auto"
  defaultTheme: "auto"

  gitRepo: "https://github.com/rolandjitsu/rolandsdev.blog"

  dateFormat: "2006-01-02"

  images: ["/images/avatar_sm.png"]

  # https://hugodoit.pages.dev/pwa-support
  enablePWA: yes

  # license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # TODO: Doesn't work!
  # https://github.com/HEIGE-PCloud/DoIt/issues/475
  # bundle: yes

  header:
    # "fixed"/"normal"/"auto"
    desktopMode: "fixed"
    mobileMode: "auto"
    # "switch"/"select"
    themeChangeMode: "switch"
    title:
      name: "Roland's Dev Blog"
      typeit: yes

  footer:
    enable: yes
    hugo: yes
    hostedOn: '<a title="Netlify" href="https://www.netlify.com/" target="_blank" rel="noopener noreffer">Netlify</a>'
    copyright: yes
    author: yes
    # since: 2020
    # license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Posts
  section:
    paginate: 10
    dateFormat: "01-02"
    rss: 10

  # Category/Tags
  list:
    paginate: 10
    dateFormat: "01-02"
    rss: 10

  home:
    profile:
      enable: yes
      avatarURL: "/images/avatar_sm.webp"
      title: ""
      subtitle: "A collection of dev guides, tutorials and thoughts on various tech stacks, tools and programming languages."
      social: no
      posts:
        enable: yes
        paginate: 4

  page:
    # https://hugodoit.pages.dev/theme-documentation-content/#extended-markdown-syntax
    ruby: no
    fraction: no
    fontawesome: yes
    linkToMarkdown: yes
    linkToSource: "https://github.com/rolandjitsu/rolandsdev.blog/blob/main/content/{path}"
    linkToEdit: "https://github.com/rolandjitsu/rolandsdev.blog/edit/main/content/{path}"
    linkToReport: "https://github.com/rolandjitsu/rolandsdev.blog/issues/new"
    pageStyle: "normal"
    seriesNavigation: yes
    toc:
      enable: yes
      keepStatic: no
      auto: yes
    code:
      copy: yes
      maxShownLines: 100
    table:
      sort: yes
    math:
      enable: no
    comment:
      giscus:
        enable: yes
        # owner/repo
        dataRepo: "rolandjitsu/rolandsdev.blog"
        dataRepoId: "R_kgDOHBwhkg"
        dataCategory: "General"
        dataCategoryId: "DIC_kwDOHBwhks4COZWW"
        dataMapping: "pathname"
        dataReactionsEnabled: "1"
        dataEmitMetadata: "0"
        dataInputPosition: "bottom"
        lightTheme: "light"
        darkTheme: "dark"
        dataLang: "en"

  sponsor:
    enable: yes
    bio: "If you find this post helpful, please consider sponsoring."
    link: "https://github.com/sponsors/rolandjitsu"
    custom: ""

  verification:
    google: ""

  analytics:
    google:
      id: "UA-129682120-2"
      anonymizeIP: yes

author:
  name: "rolandjitsu"
  email: "rolandjitsu@gmail.com"
  link: "https://github.com/rolandjitsu"

# https://gohugo.io/content-management/urls/#permalinks
permalinks:
  offline: /offline

# https://gohugo.io/getting-started/configuration/#taxonomies
# https://gohugo.io/content-management/taxonomies#configure-taxonomies
taxonomies:
  author: "authors"
  category: "categories"
  tag: "tags"
  series: "series"
